datasets:
  vctk:
    info_file_path: /path/to/speaker-info.txt
    wavs_folder_path: path/to/wav16/
    conds_speaker:
      pase_seed_folder_path: /path/to/wav16_pase_seed/
    conds_utterance:
      acoustic_folder_path: /path/to/wav16_conds_acoustic/
      linguistic_folder_path: /path/to/wav16_conds_linguistic/
    sampling_freq: 16000
    n_speakers: 108
    enabled: True
  cmu_artic:
    info_file_path: /path/to/info.txt
    conds_speaker:
      pase_seed_folder_path: /path/to/wav16_pase_seed/
    conds_utterance:
      acoustic_folder_path: /path/to/wav16_conds_acoustic/
      linguistic_folder_path: /path/to/wav16_conds_linguistic/
    sampling_freq: 16000
    n_speakers: 18
    enabled: True
pase:
  config_file_path: /path/to/data/pase.cfg
  trained_model_path: /path/to/data/PASE.ckpt