datasets:
  vctk:
    info_file_path: /db/vctk/speaker-info.txt
    wavs_folder_path: /db/vctk/wav16_trimmed/
    conds_utterance:
      acoustic_folder_path: /db/vctk/wav16_trimmed_conds_acoustic/
      linguistic_folder_path: /db/vctk/wav16_trimmed_conds_linguistic/
    sampling_freq: 16000
    n_speakers: 108
    enabled: True
  cmu_artic:
    info_file_path: /db/cmu_artic/info.txt
    wavs_folder_path: /db/cmu_artic/wav16_trimmed/
    conds_utterance:
      acoustic_folder_path: /db/cmu_artic/wav16_trimmed_conds_acoustic/
      linguistic_folder_path: /db/cmu_artic/wav16_trimmed_conds_linguistic/
    sampling_freq: 16000
    n_speakers: 18
    enabled: True
pase:
  config_file_path: /Users/DavidAlvarezDLT/PycharmProjects/samplernn_pytorch/data/pase.cfg
  trained_model_path: /Users/DavidAlvarezDLT/PycharmProjects/samplernn_pytorch/data/PASE.ckpt